export const REQUEST_NEW_DRIVER_START = "REQUEST_NEW_DRIVER_START";
export const REQUEST_NEW_DRIVER_SUCCESS = "REQUEST_NEW_DRIVER_SUCCESS";
export const REQUEST_NEW_DRIVER_FAILED = "REQUEST_NEW_DRIVER_FAILED";
